openapi: 3.0.0
info:
  title: API de Gestión de Usuarios y Créditos
  version: 1.0.0
  description: >
    API que permite gestionar usuarios y créditos en una base de datos PostgreSQL.

paths:
  /usuarios:
    post:
      summary: Registrar nuevo usuario
      description: Registra un nuevo usuario en la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            example:
              nombre: Juan
              apellido: Pérez
              correo: juan@example.com
              cedula: 1234567890
              celular: 0987654321
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              example:
                id: 1
                mensaje: Usuario creado con éxito

    get:
      summary: Obtener todos los usuarios
      description: Retorna la lista de todos los usuarios en la base de datos.
      responses:
        '200':
          description: Lista de usuarios recuperada exitosamente
          content:
            application/json:
              example:
                - id: 1
                  nombre: Juan
                  apellido: Pérez
                  correo: juan@example.com
                  cedula: 1234567890
                  celular: 0987654321

  /creditos/{numero_cuenta}:
    post:
      summary: Solicitar nuevo crédito
      description: Solicita un nuevo crédito asociado a una cuenta específica.
      parameters:
        - in: path
          name: numero_cuenta
          required: true
          description: Número de cuenta asociado al crédito.
          schema:
            type: string
            example: "1234567890"
      requestBody:
        required: true
        content:
          application/json:
            example:
              monto: 10000.0
              tasa_interes: 0.05
              plazo_meses: 12
      responses:
        '201':
          description: Crédito solicitado exitosamente
          content:
            application/json:
              example:
                mensaje: Crédito solicitado exitosamente

  /creditos/{credito_id}:
    put:
      summary: Aprobar crédito
      description: Aprueba un crédito existente.
      parameters:
        - in: path
          name: credito_id
          required: true
          description: ID del crédito a aprobar.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Crédito aprobado exitosamente
          content:
            application/json:
              example:
                mensaje: Crédito aprobado exitosamente

    delete:
      summary: Rechazar crédito
      description: Rechaza un crédito existente.
      parameters:
        - in: path
          name: credito_id
          required: true
          description: ID del crédito a rechazar.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Crédito rechazado exitosamente
          content:
            application/json:
              example:
                mensaje: Crédito rechazado exitosamente

  /creditos/{usuario_id}/reporte:
    get:
      summary: Generar reporte de créditos
      description: Genera un reporte de todos los créditos asociados a un usuario específico.
      parameters:
        - in: path
          name: usuario_id
          required: true
          description: ID del usuario para el reporte.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Reporte de créditos generado exitosamente
          content:
            application/json:
              example:
                creditos:
                  - id: 1
                    cliente_nombre: Juan Pérez
                    monto: 10000.0
                    tasa_interes: 0.05
                    plazo_meses: 12

  /creditos/{usuario_id}/amortizacion:
    get:
      summary: Generar tabla de amortización
      description: Genera una tabla de amortización para los créditos asociados a un usuario específico.
      parameters:
        - in: path
          name: usuario_id
          required: true
          description: ID del usuario para la tabla de amortización.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tabla de amortización generada exitosamente
          content:
            application/json:
              example:
                mensaje: Tabla de amortización generada exitosamente


components:
  schemas:
    Credito:
      type: object
      properties:
        id:
          type: integer
          description: ID del crédito
        cliente_nombre:
          type: string
          description: Nombre del cliente
        monto:
          type: number
          description: Monto del crédito
        tasa_interes:
          type: number
          description: Tasa de interés del crédito
        plazo_meses:
          type: integer
          description: Plazo en meses del crédito
    Usuario:
      type: object
      properties:
        id:
          type: integer
          description: ID del usuario
        nombre:
          type: string
          description: Nombre del usuario
        apellido:
          type: string
          description: Apellido del usuario
        correo:
          type: string
          description: Correo electrónico del usuario
        cedula:
          type: string
          description: Número de cédula del usuario
        celular:
          type: string
          description: Número de celular del usuario

    CuentaAhorros:
      type: object
      properties:
        id:
          type: integer
          description: ID de la cuenta de ahorros
        usuario:
          $ref: '#/components/schemas/Usuario'
          description: Objeto de tipo Usuario asociado a la cuenta de ahorros
        numero_cuenta:
          type: string
          description: Número de cuenta de la cuenta de ahorros
        saldo:
          type: number
          description: Saldo actual en la cuenta de ahorros

